repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    -   id: check-added-large-files
        args: ['--maxkb=10000']
    -   id: trailing-whitespace
    -   id: detect-private-key
    -   id: requirements-txt-fixer
    -   id: end-of-file-fixer

- repo: https://github.com/PyCQA/isort
  rev: 5.10.1
  hooks:
    - id: isort

-   repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
    -   id: flake8
